### PR TITLE
Improve streaming logs performance

### LINKED ISSUE #286: Container#streaming_logs performance issues
Contaniner::streaming_logs method seems to store all streamed log items in memory which is kinda bad thing if you stream lots of logs. Could it be changed so that method only yields those log items without keeping them in memory?

### PR DESCRIPTION
**Pull request by jakolehm**
This PR adds possibility to define message stack size. By default stack has no limits so it should behave like before. But if you give `stack_size` option, the stack will be limited to that size. So basically if you define `stack_size: 0` then it won't collect any log items to stack/memory. 

Fixes #286

### CODE REVIEW

**Comment by jakolehm** [comment]
I didn't manage to record vcr files correctly (tried with boot2docker and vagrant) and that's why one test fails.

**Comment by jakolehm** [comment]
@tlunter what do you think, will you accept this PR if I somehow manage to fix vcr files?

**Comment by tlunter** [comment]
@jakolehm looks good now. Thanks.

**Comment by tlunter** [comment]
Released in v1.22.0

**Pull request merged**
