### PR TITLE
Add network command

### PR DESCRIPTION
**Pull request by smgt**
This will add the basic `docker network` commands. It will make it possible to create, delete, connect, disconnect and list docker networks.

There are no tests. I ran the test suite and there are so many tests not working with docker 1.9. I started fixing all the tests but then I will break the tests on older versions of docker.

### CODE REVIEW

**Comment by tlunter** [comment]
@smgt I've got a pull ready that'll fix the problems with 1.9 and make it so we don't record VCRs anymore. Care to try and add tests once that merges?

**Comment by smgt** [comment]
With pleasure! Is it the `fix-tests` branch?

**Comment by tlunter** [comment]
It is! Thanks @smgt

**Comment by smgt** [comment]
I ran the tests and everything seems green. That is nice! I rebased and force pushed. This branch depends on `fix-tests` branch.

```
Finished in 3 minutes 19.4 seconds (files took 0.15968 seconds to load)
169 examples, 0 failures, 3 pending
```

**Comment by smgt** [comment]
I will fix tests for this PR also now that they work.

**Comment by tlunter** [comment]
Thanks @smgt!

**Comment by smgt** [comment]
Tests are added, they fail on travis since travis don't run docker 1.9. Dunno what version they are running. The tests pass when I run them locally on 1.9. I rebased on top of your `fix-tests` branch to be able to run the tests. So please merge #340 before merging this PR. :smile_cat:

**Comment by SydOps** [comment]
I try to have to review, but why there are so many files listed but no changed? Could you please raise a new pull request? 

It makes me confused when review your commits.

**Comment by smgt** [comment]
They are deleted files. And if you read the thread you will see that I wan't #340 in master before we merge this. That will remove all @tlunter's commits from this PR.

**Comment by tlunter** [comment]
@smgt sorry about that. Just merged!

**Comment by smgt** [comment]
I've rebased on master now, this PR should have passing tests when using docker 1.9. On travis they use 1.8.2 ( https://travis-ci.org/swipely/docker-api/jobs/95024331#L173 ). Maby check version of docker when running network tests? WDYT @tlunter

**Comment by tlunter** [comment]
@smgt I've got another fix in the works.  #349 will let us test against many different docker version. You can see what I'm doing [here](https://github.com/swipely/docker-api/blob/add-archive/spec/spec_helper.rb) and [here](https://github.com/swipely/docker-api/blob/add-archive/spec/docker/container_spec.rb) to handle this.

**Comment by smgt** [comment]
Nice, added a filter to make the network tests only run on 1.9.

**Comment by smgt** [comment]
So, how do you feel about merging this @tlunter ? I've rebased on top of master and #349 is now in master.

**Comment by gionn** [comment]
@tlunter something is blocking merge?

**Comment by tlunter** [comment]
I will be trying to final review this in the coming days.  Sorry about the delay

**Comment by tlunter** [comment]
Closed and re-opened to trigger travis.

**Comment by tlunter** [comment]
@smgt @gionn released in v1.25.0, let me know if you have any issues!

**Comment by smgt** [comment]
Yay! TY! :+1:

**Comment by fishnix** [comment]
:dancers:

**Pull request merged**
