### PR TITLE
Add :format option to *top* method

### PR DESCRIPTION
**Pull request by n-rodriguez**
Patch for https://github.com/swipely/docker-api/issues/352

### CODE REVIEW

**Comment by tlunter** [comment]
Closing and reopening PR in an attempt to trigger travis build.

**Comment by franz-josef-kaiser** [comment]
@tlunter You can simply re-run the build on Travis (the round arrow in the upper right corner) in the Travis UI when looking at a single build.

**Comment by tlunter** [comment]
@franz-josef-kaiser in this particular case there wasn't already a build.  We had PR builds turned off, so closing and re-opening was the only way to trigger it.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Thank you!

**Comment by tlunter** [comment]
Released in v1.33.4

**Pull request merged**
