### PR TITLE
add the :wait parameter to container.exec

### PR DESCRIPTION
**Pull request by hyz0906**
add the `:wait` parameter when call `exec.start!`

### CODE REVIEW

**Comment by tlunter** [comment]
I don't believe the ExecStart endpoint takes `wait` as a parameter.  Did this work locally?

**Comment by hyz0906** [comment]
I have tested this locally and it works well.
https://github.com/swipely/docker-api/blob/master/lib/docker/exec.rb#L51
```
def start!(options = {}, &block)
    tty = !!options.delete(:tty)
    detached = !!options.delete(:detach)
    stdin = options[:stdin]
    read_timeout = options[:wait] 
    ......
```

**Comment by tlunter** [comment]
Ah, forgot that was there. Thanks!

**Comment by tlunter** [comment]
Released in v1.30.1

**Pull request merged**
