### PR TITLE
Use Docker APT repos to install Docker. 

### PR DESCRIPTION
**Pull request by someara**
This is the preferred installation method. It lets us use the dynamically compile binaries and ensures OS deps such as cgroups are set up properly.

### CODE REVIEW

**Comment by tlunter** [comment]
I am very confused why these are all failing.

**Comment by tlunter** [comment]
The volume examples are failing oddly, but that might be actually our handling.  I'm confused by the tests that talk to the docker hub.  Those shouldn't be failing...  @someara any ideas?

**Comment by someara** [comment]
From what I can tell, the "install_dependencies" script was never actually working at all.

- The Travis trusty machines come with a docker service running out of the box
- The .travis.yml was attempting to start a service from /opt
- That script was actually failing to start the daemon.. "docker -d" was deprecated in 1.7.1 in favor of "docker daemon". The "set -e" at the top of the script was failing to catch it because of the fork into the background via the amperstand.
- docker --version was reporting the version of the client binary picked up from opt...
- The actual specs were being ran against the out-of-the-box docker service, as there were no DOCKER_HOST env vars pointing it elsewhere.

I'm going to keep tweaking this PR until I can figure out why master is green. Stay tuned =)

-s

**Comment by tlunter** [comment]
*smacks head* Makes sense. I didn't realize they started a daemon by default. Thanks @someara

**Comment by tlunter** [comment]
@someara The reason the docker hub stuff is failing is because the secure env variables aren't populated on builds from forks.  If we merge, we'll see those pass.

**Comment by someara** [comment]
*smacks forehead* of course! =)
-s

**Comment by someara** [comment]
Here's a technique to avoid the need for the secure ENV vars... Set up a
private registry and use insecure creds in the test the relevant bits.

https://github.com/chef-cookbooks/docker/blob/a471c2addb051324790321babb0976790a232187/test/cookbooks/docker_test/recipes/image.rb#L222

https://github.com/chef-cookbooks/docker/blob/a471c2addb051324790321babb0976790a232187/test/cookbooks/docker_test/recipes/registry.rb

**Comment by someara** [comment]
Okay so...

It turns out that the previous travis config was really testing against Docker 1.8.2 every time.
This PR sets up the full matrix, but comments out everything but 1.8.2 for starters.

-s

**Comment by tlunter** [comment]
Merged this commit in: https://github.com/swipely/docker-api/pull/386

**Pull request closed without merging**
