### PR TITLE
Use bundler cache on Travis CI

### PR DESCRIPTION
**Pull request by dlackty**

### CODE REVIEW

**Comment by tlunter** [comment]
Good call, thanks.

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious, bundler caching was available since December 17, 2014, but I see you just enabled it in this pull request (about a year later). Any reasons, please? 

Thanks.

**Comment by dlackty** [comment]
@Taher-Ghaleb I remembered at the time bundler caching was introduced, it was off by default. Explicit config like this PR was required to enable the caching.

**Comment by Taher-Ghaleb** [comment]
I see. Thanks, @dlackty, for your response.

**Pull request merged**
