### PR TITLE
drop 1.9 it is dead

### PR DESCRIPTION
**Pull request by grosser**
@tlunter

### CODE REVIEW

**Comment by grosser** [comment]
the credentials seem to still fail ...       logs in and sets the creds (FAILED - 1)

**Comment by grosser** [comment]
added a skip for the tests with credentials ... seems to work fine locally, but not on travis ...

**Comment by grosser** [comment]
some test from with this ... not sure what's going on there :(

```
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/info: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Comment by grosser** [comment]
@tlunter would love to get some direction / help here if you know why this is failing

**Comment by tlunter** [comment]
@grosser let's also drop DOCKER_VERSION 1.6.2.

**Comment by tlunter** [comment]
Trying to understand the other failures now.

**Comment by tlunter** [comment]
@grosser can you apply this diff?

```
diff --git a/script/install_docker.sh b/script/install_docker.sh
index 1f76ce5..594b494 100755
--- a/script/install_docker.sh
+++ b/script/install_docker.sh
@@ -28,8 +28,6 @@ then
     cp script/docker.conf /etc/init/docker.conf
     cp script/docker /etc/init.d/docker
     chmod +x /etc/init.d/docker
-else
-    service docker stop
+    service docker start
 fi

-service docker start
```

Seems the error is due to the restart and the docker0 bridge persisting.  Not really sure I care to handle that case in our automated test suite, so let's just not restart the daemon :)

**Comment by grosser** [comment]
removing the start does not work ... restart seems to work better ... still some failures

```
$ docker info
An error occurred trying to connect: Get http:///var/run/docker.sock/v1.21/info: read unix /var/run/docker.sock: connection reset by peer

```

**Comment by tlunter** [comment]
@grosser apt-get install will start docker, i want to avoid restarting it at all.

**Comment by grosser** [comment]
without the start it was not running ... I'll retry that ...

**Comment by grosser** [comment]
that looks good ...

**Comment by grosser** [comment]
first run had 1 random failure  `spec/docker/event_spec.rb:90` ... 

good to merge or should I try removing the skips now ?

**Comment by tlunter** [comment]
@grosser sorry, I thought the skip was a good idea.

**Comment by grosser** [comment]
reverted it just to try it out ... but we need it :)

... all green now ... merge ?

**Pull request merged**
