### PR TITLE
ignore files based on dockerignore

### LINKED ISSUE #313: Support for .dockerignore files in build context.
Hi,

I'm transitioning from the docker cli to this gem and I was wondering wether there is support for
`.dockerignore` files? I have a `.dockerignore` in my build context directory and in my case that makes a difference of 300-400 MB.

https://docs.docker.com/reference/builder/
> To increase the build’s performance, exclude files and directories by adding a .dockerignore file to the context directory.

### PR DESCRIPTION
**Pull request by grosser**
@tlunter 

fixes #313 @wpp

### CODE REVIEW

**Comment by tlunter** [comment]
Can you rebase this on master now @grosser ?

Also, since this is here we don't need #433 right?

**Comment by grosser** [comment]
preferably merge 433 first since it's a clean commit/refactor ... then this

**Comment by grosser** [comment]
@tlunter ready!

**Comment by grosser** [comment]
@tlunter got time to review this ?

**Comment by grosser** [comment]
@tlunter would love some feedback :)

**Pull request merged**
