### PR TITLE
Verify cache support works

### LINKED ISSUE #269: Docker::Image.build_from_dir breaks caching
The mtime on all the files is updated and thus breaks caching.

### PR DESCRIPTION
**Pull request by tlunter**
@bfulton @nahiluhmot 

Will fix #269

Pulls in the rubygems code that builds each file in the tar.

### CODE REVIEW

**Comment by nahiluhmot** [comment]
:100:

**Comment by szubster** [comment]
When is it possible that we will have release with this feature?
It is a real to pain to use serverspec with docker without proper cache.

**Comment by tlunter** [comment]
Released in v1.21.3

**Comment by szubster** [comment]
Great :+1: 
Thanks for quick response.

**Pull request merged**
