### PR TITLE
Added support for docker volume API (for Docker 1.9)

### PR DESCRIPTION
**Pull request by cbalducci**
This adds docker volume basic commands (ALL, GET, CREATE and DELETE). It enables docker volume command.

First time writing ruby and first time using rake so i'll happily read your comments and thoughts

### CODE REVIEW

**Comment by tlunter** [comment]
@cbalducci awesome, I've got a PR that I'm looking to merge real soon that'll remove all the VCR files.  After that, can you rebase your branch and remove any additional files you've got there? That way we can really analyze these additions :) Thanks!

**Comment by cbalducci** [comment]
@tlunter sure, i suppose you're talking about PR https://github.com/swipely/docker-api/pull/340, right?

**Comment by tlunter** [comment]
That's the one!

**Comment by cbalducci** [comment]
done

> Finished in 7 minutes 51 seconds (files took 0.2551 seconds to load)
> 173 examples, 0 failures, 3 pending

**Comment by cbalducci** [comment]
Hey @tlunter, what's blocking this from getting merged? let me know if i can help :)

**Comment by tlunter** [comment]
@cbalducci you'll need to rebase before we can merge. will review after that.

**Comment by cbalducci** [comment]
tried to rebase, it's a mess (mainly because i'm not very good at git)
Since cbalducci/add-volume can merge with swipely/master it's ok if we close this PR and open another one?

**Comment by tlunter** [comment]
That's what this PR is attempting to do. I'll see if I can do a rebase later on today.

**Comment by awsmsrc** [comment]
this would make what I'm working on soooo much easier.
+1 for getting this merged and will help if possible

**Comment by tlunter** [comment]
Fixed up and released in v1.26.0.  Thanks @cbalducci

**Comment by cbalducci** [comment]
@tlunter awesome! thank you and sorry for the mess :smile:

**Comment by awsmsrc** [comment]
This pr could probably be closed??

I think we could also add some info on the new functionality in the README.md?

**Pull request closed without merging**
