### PR TITLE
Add mutex for threadsafe operation

### PR DESCRIPTION
**Pull request by tlunter**
@nahiluhmot @bfulton

Would take care of #248.  Seems there is no thread safe `cd` in ruby, so a mutex will have to do.  This method should be quick anyway.

### CODE REVIEW

**Comment by bfulton** [comment]
Let's not prevent concurrent builds in different dirs; maybe change `create_dir_tar_mutex` to take directory and return the mutex from a hash keyed by directory?

**Comment by tlunter** [comment]
@bfulton the concern is actually concurrent builds in different dirs.  When we run this command in two threads, for two separate directories, the current working directory of the whole process shifts, and the first thread is now operating on a different directory from intended.

**Comment by bfulton** [comment]
Ah. Maybe we should fork then?

**Comment by bfulton** [comment]
Or, even better, let's create the tar without changing our directory?

**Comment by tlunter** [comment]
@bfulton The problem with not changing our directory is the resulting tar has all the paths relative to our current directory.  If the directory appears below the currently directory, like `../some-other-place`, `Archive::Tar::Minitar` will just fail.

**Comment by bfulton** [comment]
@tlunter but something like this could work:

https://github.com/atoulme/minitar/compare/atoulme:cc7a41e...bfulton:cb3b2a1

**Pull request closed without merging**
